### PR TITLE
Allow watching additional directories

### PR DESCRIPTION
**Pull request by arp242**
Problem: I'm working on a Go application with html/template files and I
need to manually restart the binary every time to see any change.

Solution: allow giving an additional list of directories to watch. For example:

	var tpl = loadTpl()

	func loadTpl() *template.Template {
		t, err := template.New("").Option("missingkey=error").ParseGlob("tpl/*.gohtml")
		if err != nil {
			log.Println(err)
		}
		return t
	}

	func main() {
		go func() {
			err := reload.Do(log.Printf, reload.Dir("./tpl", func() {
				log.Printf("reloading templates")
				tpl = loadTpl()
			}))
		}()
	}

Which seems to work pretty well. Great success!

This should be a backwards-compatible change.

### CODE REVIEW

**Comment by arp242** [comment]
Okay, this is the last one for now :-) Turns out that a bunch of use cases that aren't really used in Teamwork didn't work so well. This repo got a bunch of stars already so I'd rather modify this instead of maintaining my own copy.

Could you also please create a new version after merging?

	git tag v1.2
	git push --tags

Thanks :-)

**Comment by ripexz** [comment]
Fix lint error please 😊

**Comment by NSLeoFont** [comment]
Please remove me from this notifications. I left TW 4 months ago ;)
Cheers. Leo

**Comment by ripexz** [comment]
> Please remove me from this notifications. I left TW 4 months ago ;)
> Cheers. Leo

It's a public repository, just unwatch any repos you don't want to receive notifications about (button next to star/fork) and also unsubscribe from this PR since you're now participating 🙃 

Screenshot 2019-03-19 at 10 21 11

**Comment by arp242** [comment]
Also see https://github.com/notifications/subscriptions

**Comment by arp242** [comment]
> Fix lint error please blush

Oops; don't see that through chat bot any more :-)

I silenced it, as it's not a very useful warning in this case.

**Pull request merged**
